apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecarinjector.fullname" . }}
  labels:
{{ include "sidecarinjector.labels" . | indent 4 }}
data:
  sidecarconfig.yaml: |
    containers:
      - name: fluentd
        image: {{ .Values.fluentd.repository }}:{{ .Values.fluentd.tag }}
        imagePullPolicy: {{ .Values.fluentd.pullPolicy }}
        env:
          - name: API_KEY
            value: {{ .Values.newrelic.apikey }}
          - name: BASE_URI
            value: {{ .Values.newrelic.baseuri }}
          - name: LOG_LEVEL
            value: debug
        resources
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - name: logs
            mountPath: /var/log/application/
    volumes:
      - emptyDir: {}
        name: logs
    volumeMounts:
      - name: logs
        mountPath: /var/log/application/
  mutationconfig.yaml: |
    mutationConfigs:
      - name: "fluentd"
        annotationNamespace: "fluentd.k8s.meetings.io"
        annotationTrigger: "inject"
        containers: ["fluentd"]
        volumeMounts: ["logs"]
        volumes: ["logs"]
        ignoreNamespaces: []
        whitelistNamespaces: []
