apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecarinjector.fullname" . }}
  labels:
{{ include "sidecarinjector.labels" . | indent 4 }}
data:
  sidecarconfig.yaml: |
    containers:
      - name: fluentd
        image: {{ .Values.fluentd.repository }}:{{ .Values.fluentd.tag }}
        imagePullPolicy: {{ .Values.fluentd.pullPolicy }}
        env:
          - name: API_KEY
            value: {{ .Values.newrelic.apikey }}
          - name: BASE_URI
            value: {{ .Values.newrelic.baseuri }}
          - name: LOG_LEVEL
            value: debug
  mutationconfig.yaml: |
    mutationConfigs:
      - name: "fluentd"
        annotationNamespace: "fluentd.k8s.meetings.io"
        annotationTrigger: "inject"
        containers: ["fluentd"]
        ignoreNamespaces: []
        whitelistNamespaces: []
