apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "sidecarinjector.fullname" . }}-selfsigned
  labels:
{{ include "sidecarinjector.labels" . | indent 4 }}
spec:
  selfSigned: {}