---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "sidecarinjector.fullname" . }}
  labels:
{{ include "sidecarinjector.labels" . | indent 4 }}
webhooks:
  - clientConfig:
      caBundle: ""
      service:
        name: {{ include "sidecarinjector.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
    failurePolicy: Ignore
    name: {{ include "sidecarinjector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    namespaceSelector:
      matchExpressions:
        - key: inject-fluentd
          operator: In
          values: ["true", "1"]
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: "Namespaced"
