---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "sidecarinjector.fullname" . }}
  labels:
{{ include "sidecarinjector.labels" . | indent 4 }}
webhooks:
  - clientConfig:
      caBundle: ""
      service:
        name: {{ include "sidecarinjector.fullname" . }}
        namespace: {{ .Values.namespace }}
        path: /mutate
    failurePolicy: Fail
    name: {{ include "sidecarinjector.fullname" . }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
